### ISSUE TITLE
Permission denied (publickeey)   ......could not read from remote repository

### ISSUE THREAD

**Issue by HajarALabri** [learn-co-curriculum/phase-0-organizing-work-on-your-computer#10]
![image](https://github.com/learn-co-curriculum/phase-0-organizing-work-on-your-computer/assets/131456889/dbce7848-6674-47c2-8e64-bc50669a60e1)

**Comment by lizbur10** [comment]
Hi @HajarALabri ! This error usually happens because the GitHub SSH key is not set up correctly. I recommend that you return to the lesson on setting up Git and GitHub and repeat the steps in the Configure Git and GitHub section. If you're still having problems after doing that, I suggest that you use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team
